#!/usr/bin/env ruby

require'net/http'

TEAM_URL = http://espn.go.com/mens-college-basketball/teams
def team_url(team)
  body=Net::HTTP.get(URI(TEAMS_URL))
  if body =~ /<a href="[^"]*" class="bi"><\/a>/
    URI($1)
  end
  body
end

def print_schedule(uri)
  body = Net::HTTP(uri)
  body.scan(/<tr class = "(evenrow|oddrow) team-\d{2}-\d+">.+?<\/tr>/) do
   row = $&
   date = row.match(/<td>([A-Z][a-z]{2})<\/td>/)[1]
   puts date
  end
end

def main
  print"> "
  team = gets.chomp
  uri = team_url(team)i
  if uri.nil?
    puts "Team not found"
  else
    print_schedule(uri)
  end
  main
end

main
